#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1337617504.6294329
__CHEETAH_genTimestamp__ = 'Mon May 21 11:25:04 2012'
__CHEETAH_src__ = 'base_html.tmpl'
__CHEETAH_srcLastModified__ = 'Mon May 21 11:01:37 2012'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class base_html(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(base_html, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html>
<html>
<head>
<title>Cybercommons Catalog</title>
<!--BaseJavascript-->
<script type="text/javascript" src="http://static.cybercommons.org/js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="http://static.cybercommons.org/js/jquery.jeditable.mini.js"></script>
<script type="text/javascript" src="http://static.cybercommons.org/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" src="http://static.cybercommons.org/mstacy/jquery.contextMenu.js"></script>
<script type="text/javascript" src="http://static.cybercommons.org/css/bootstrap/js/bootstrap.min.js"></script>
<!--Base CSS-->
<link type="text/css" href="http://static.cybercommons.org/css/cybercomui/jquery-ui-1.8.13.custom.css" rel="Stylesheet"/>
<link type="text/css" href="http://static.cybercommons.org/css/bootstrap/css/bootstrap.min.css" rel="Stylesheet"/>
<link type="text/css" href="http://static.cybercommons.org/css/bootstrap/css/cybercommons.css" rel="Stylesheet"/>
<link type="text/css" href="http://static.cybercommons.org/css/cybercom/style.css" rel="Stylesheet"/>
<!--Custom App JS-CSS-->
<script type="text/javascript" src="http://static.cybercommons.org/mstacy/json.js"></script>
<link type="text/css" href="http://static.cybercommons.org/mstacy/json.css" rel="Stylesheet"/>
<script>
$(document).ready(function() { 
    $('a[data-toggle="tab"]').on('shown', function (e) {
        if(e.target.name==\'tabs-3\'){
            if($(\'#json_editor_loc\').html()==\'\'){
            json_editor(\'json_editor_loc\',$(\'#jsoninput_location\').val());
            apply_editlets();
        }}
        if(e.target.name==\'tabs-2\'){
            if($(\'#json_editor_meta\').html()==\'\'){
            json_editor(\'json_editor_meta\',$(\'#jsoninput_meta\').val());
            apply_editlets();
        }}
    });
});
</script>
</head>
</head>
<body>
<div class="navbar" style="margin-bottom: 1px;">
     <div class="navbar-inner" style="background: #1A5A80;">
          <div class="container-fluid">
               <a class="brand" href="/catalog1/data/"  style="color: white;">Cybercommons Catalog</a>

                                <div class="nav-collapse">
                                        <ul class="nav">
                                                <li><a href="/catalog1/data/">Home</a></li>
                                                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Edit <b class="caret"></b></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a data-toggle="modal" href="#new_commons">New Data Commons</a></li>
                                                        <li class="divider"></li>
                                                        <li><a href="#">Another action</a></li>
                                                        <li><a href="#">Something else here</a></li>
                                                        <li class="divider"></li>
                                                        <li><a href="#">Separated link</a></li>
                                                    </ul>
                                                </li>
                                                <li><a data-toggle="modal" href="#about">About</a></li>


                                        </ul>
                                </div>
                                        <ul class="nav pull-right">
                                                <li><a data-toggle="modal" href="#contact">Contact</a></li>
                                                <li><a data-toggle="modal" href="/accounts/profile/">Welcome, ''')
        _v = VFFSL(SL,"user",True) # u'@user' on line 63, col 93
        if _v is not None: write(_filter(_v, rawExpr=u'@user')) # from line 63, col 93.
        write(u'''</a></li>
                                        </ul>
                        </div>
                </div>
        </div>
''')
        _v = VFFSL(SL,"body",True) # u'@body' on line 70, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'@body')) # from line 70, col 1.
        write(u'''
</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_base_html= 'respond'

## END CLASS DEFINITION

if not hasattr(base_html, '_initCheetahAttributes'):
    templateAPIClass = getattr(base_html, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(base_html)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=base_html()).run()


